[book]
authors = ["Subramanian"]  # Or your authors
description = "This is a sample book"
language = "en"
multilingual = false
src = "src"
version = "v1.0"
title = "My First Mdbook"

# [output.html]
# additional-css = ["theme/custom.css"]
