name: Update Releases in mdBook

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests
      
      - name: Set Replacement Text
        id: set-replacement-text
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "REPLACEMENT_TEXT=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "push" ]; then
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "REPLACEMENT_TEXT=${{ github.ref_name }} (${SHORT_SHA})" >> $GITHUB_ENV
          fi

      - name: Update version in file
        uses: richardrigutins/replace-in-files@v2
        with:
          files: 'theme/index.hbs'
          search-text: 'RELEASE_VERSION'
          replacement-text: ${{ env.REPLACEMENT_TEXT }}

      - name: Debug
        run: cat theme/index.hbs

      - name: Install mdBook
        uses: extractions/setup-crate@v1
        with:
          repo: rust-lang/mdBook

      - name: Build the book
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: build
          publish_dir: ./book
