name: Update Releases in mdBook

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch release information and update SUMMARY.md
        run: python fetch_releases.py

      - name: Debug
        run: cat theme/index.hbs

      - name: Install mdBook
        uses: extractions/setup-crate@v1
        with:
          repo: rust-lang/mdBook

      - name: Build the book
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: build
          publish_dir: ./book
